//addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"        % "2.5.0")
//addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "2.0.7")
//addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"% "0.9.2")
//addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.5.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.3.0")
addSbtPlugin("io.spray"     % "sbt-revolver" % "0.10.0")
addSbtPlugin("de.gccc.sbt"  % "sbt-jib"      % "1.3.7")
